#!/bin/bash

# Create Virtual Environment
echo "Creating virtual environment..."
python3 -m venv venv
source venv/bin/activate

# Install the required packages
echo "Installing required packages..."
pip3 install pix2tex[train] gpustat opencv-python-headless wandb

echo Checking for GPU
# Check if gpus are available and if no gpus are available confirm with user to continue
if [ -z "$(gpustat -i)" ]; then
    echo "No GPUs available. Training will take a long time and you will need to modify the config file to use CPU."
    read -p "Continue? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Download and extract the data
echo Downloading data
python3 scripts/download_and_extract_data.py && \
echo Reorganizing data for training
python3 scripts/reorganize_data.py

# Generate the dataset
echo Generate Lukas dataloader files
python3 -m pix2tex.dataset.dataset -i dataset/data/train -e dataset/data/train.lst -o dataset/data/train.pkl
python3 -m pix2tex.dataset.dataset -i dataset/data/val -e dataset/data/val.lst -o dataset/data/val.pkl

# Generate the tokenizer
echo Generate tokenizer
python3 -m pix2tex.dataset.dataset --equations dataset/data/im2latex_formulas.final.lst --vocab-size 8000 --out custom/tokenizer.json

# Train the model
echo Using custom config file in custom/config.yaml
echo Training
python3 -m pix2tex.train --config custom/config.yaml
