#!/bin/bash

source venv/bin/activate


# Generate the tokenizer
echo Generate tokenizer
python3 -m pix2tex.dataset.dataset --equations dataset/data/im2latex_formulas.final.lst --vocab-size 8000 --out custom/full_tokenizer.json

# Generate the dataset
echo Generate Lukas dataloader files
python3 -m pix2tex.dataset.dataset -i dataset/data/train -e dataset/data/train.lst -o dataset/data/train.pkl -t custom/full_tokenizer.json
python3 -m pix2tex.dataset.dataset -i dataset/data/val -e dataset/data/val.lst -o dataset/data/val.pkl -t custom/full_tokenizer.json


# Train the model
echo Using custom config file in custom/full_tok_config.yaml
echo Training
python3 -m pix2tex.train --config custom/full_tok_config.yaml
